#yaml is able to contain multiple configurations in single file separated with '---'
spring:
  application:
    name: discovery-server
eureka:
#  server:
#    eviction-interval-timer-in-ms: 5000
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/, http://localhost:8801/eureka/, http://localhost:8802/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}    
---
spring:
  profiles: peer1
server:
  port: 8800  
eureka:
  instance:
    metadata-map:
      zone: zone1
---
spring:
  profiles: peer2
server:
  port: 8801
eureka:
  instance:
    metadata-map:
      zone: zone2
---
spring:
  profiles: peer3  
server:
  port: 8802
eureka:
  instance:
    metadata-map:
      zone: zone3
#Eureka server includes eureka-client. running with stand-alone server needs to deactivate client configurations. but peer-to-peer server doesn't.
#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false