spring:
  application:
    name: zuul-api-gateway #name should be equal to bootstrap's one
server:
  port: ${port:8888}
zuul:
  prefix: /api
  routes:
    client:
      path: /client/**
      service-id: client-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8800/eureka/, http://localhost:8801/eureka/, http://localhost:8802/eureka/